Repository boostcampwm-2024/web15-OctoDocs, pull requests merged in 2024-12, with the labels that each got.

#346 yjs, 쿼리 관련 데이터 흐름 변경
  apps/backend/src/app.module.ts
  apps/backend/src/yjs/yjs.service.ts
  apps/frontend/src/features/canvas/model/useCanvas.ts
  apps/frontend/src/features/canvas/ui/Canvas/index.tsx
  apps/frontend/src/features/editor/model/useEditorTitle.ts
  apps/frontend/src/features/pageSidebar/model/useNoteList.ts
  apps/frontend/src/features/pageSidebar/ui/Tools/index.tsx
  apps/frontend/src/routeTree.gen.ts
Labels: 🐰🐣 FE, 🐛 Bug

#353 README 업데이트
  README.md
Labels: 📑 Documentation, 🐰🐣 FE, 🐧🚀😶‍🌫️ BE

#349 사용하지 않는 pages 쿼리 제거
  apps/frontend/src/features/pageSidebar/api/usePages.ts
  apps/frontend/src/features/pageSidebar/ui/Tools/index.tsx
Labels: 🐰🐣 FE, 🐛 Bug

#355 README 오타, 이미지 수정
  README.md
Labels: 📑 Documentation, 🐰🐣 FE, 🐧🚀😶‍🌫️ BE

#359 Refresh Token DB 보관 방식으로 보안성 높이기
  apps/backend/package.json
  apps/backend/src/auth/auth.controller.ts
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/auth/token/token.module.ts
  apps/backend/src/auth/token/token.service.ts
  apps/backend/src/user/user.entity.ts
  yarn.lock
Labels: ✨ Feature, 🐧🚀😶‍🌫️ BE

#365 workspace 정보조회 api 구현
  apps/backend/src/workspace/dtos/getWorkspaceResponse.dto.ts
  apps/backend/src/workspace/dtos/userWorkspace.dto.ts
  apps/backend/src/workspace/workspace.controller.spec.ts
  apps/backend/src/workspace/workspace.controller.ts
  apps/backend/src/workspace/workspace.service.spec.ts
  apps/backend/src/workspace/workspace.service.ts
Labels: ✨ Feature, 🐧🚀😶‍🌫️ BE

#360 백엔드 로직 리팩토링
  apps/backend/src/app.module.ts
  apps/backend/src/auth/strategies/kakao.strategy.ts
  apps/backend/src/auth/strategies/naver.strategy.ts
  apps/backend/src/auth/token/token.service.ts
  apps/backend/src/edge/edge.controller.ts
  apps/backend/src/node/node.controller.ts
  apps/backend/src/node/node.service.ts
  apps/backend/src/page/page.controller.ts
  apps/backend/src/page/page.service.ts
  apps/backend/src/redis/redis.service.ts
  apps/backend/src/tasks/tasks.service.ts
  apps/backend/src/upload/upload.controller.ts
  apps/backend/src/upload/upload.service.ts
  apps/backend/src/workspace/workspace.controller.ts
  apps/backend/src/workspace/workspace.module.ts
  apps/backend/src/workspace/workspace.service.spec.ts
  apps/backend/src/workspace/workspace.service.ts
  apps/backend/src/yjs/yjs.service.ts
Labels: 🐧🚀😶‍🌫️ BE, ♻️ Refactor

#370 workspace id 파싱
  apps/websocket/src/yjs/yjs.service.ts
  yarn.lock
Labels: ✨ Feature, 🐧🚀😶‍🌫️ BE

#373 노드 색상 변경 이벤트 감지 및 처리
  apps/backend/src/edge/edge.controller.spec.ts
  apps/backend/src/edge/edge.service.spec.ts
  apps/backend/src/node/node.entity.ts
  apps/backend/src/node/node.service.spec.ts
  apps/backend/src/page/page.service.spec.ts
  apps/backend/src/redis/redis.service.ts
  apps/backend/src/tasks/tasks.service.ts
  apps/websocket/src/yjs/types/node.entity.ts
  apps/websocket/src/yjs/yjs.service.ts
  apps/websocket/src/yjs/yjs.type.ts
Labels: ✨ Feature, 🐧🚀😶‍🌫️ BE

#367 워크 스페이스 라우트 보호 및 입장 권한, 공개 범위 변경, 링크 생성, main 라우트 처리
  apps/frontend/src/app/App.tsx
  apps/frontend/src/app/routeTree.gen.ts
  apps/frontend/src/app/routes/join/index.tsx
  apps/frontend/src/features/auth/model/useAuth.ts
  apps/frontend/src/features/workspace/api/workspaceApi.ts
  apps/frontend/src/features/workspace/api/workspaceStatusApi.ts
  apps/frontend/src/features/workspace/index.ts
  apps/frontend/src/features/workspace/model/useProtectedWorkspace.ts
  apps/frontend/src/features/workspace/model/workspaceMutations.ts
  apps/frontend/src/features/workspace/model/workspaceQuries.ts
  apps/frontend/src/features/workspace/model/workspaceTypes.ts
  apps/frontend/src/features/workspace/ui/ShareTool/SharePanel.tsx
  apps/frontend/src/features/workspace/ui/WorkspaceList/index.tsx
  apps/frontend/src/shared/lib/useWorkspace.ts
Labels: 🐰🐣 FE, ✨ Feature, 🐛 Bug

#377 노드 색상 변경 기능 추가
  apps/frontend/src/app/App.tsx
  apps/frontend/src/entities/node/model/nodeTypes.ts
  apps/frontend/src/entities/node/ui/NoteNode/index.tsx
  apps/frontend/src/features/canvas/model/useCanvas.ts
  apps/frontend/src/features/canvasTools/index.ts
  apps/frontend/src/features/canvasTools/ui/NodeForm/index.tsx
  apps/frontend/src/features/canvasTools/ui/NodePanel/index.tsx
  apps/frontend/src/features/canvasTools/ui/ProfilePanel/index.tsx
  apps/frontend/src/widgets/NodeToolsView/index.ts
  apps/frontend/src/widgets/NodeToolsView/ui/index.tsx
Labels: 🐰🐣 FE, ✨ Feature

#383 사이트 접속 안되는 문제 해결
  apps/frontend/src/features/pageSidebar/ui/WorkspaceNav/index.tsx
  apps/frontend/src/features/workspace/model/useProtectedWorkspace.ts
  apps/frontend/src/shared/lib/useWorkspace.ts
  apps/frontend/src/widgets/TopNavView/ui/index.tsx
Labels: 🐰🐣 FE, 🐛 Bug

#388 README 완성
  README.md
Labels: 📑 Documentation

#391 docs: BE PR 링크 수정
  README.md
Labels: 📑 Documentation, 🐛 Bug

#392 docs: README 문제해결과정 추가
  README.md
Labels: 📑 Documentation, 🐛 Bug

#396 README 피드백 위주 변경
  README.md
Labels: 📑 Documentation, 🐛 Bug

#397 실제 순서에 맞게 리드미 목차 수정
  README.md
Labels: 📑 Documentation, 🐛 Bug

#393 현재 워크스페이스 이름 표시
  apps/frontend/src/features/pageSidebar/ui/WorkspaceNav/index.tsx
  apps/frontend/src/features/workspace/index.ts
  apps/frontend/src/widgets/TopNavView/ui/index.tsx
Labels: 🐰🐣 FE, ✨ Feature

#395 로그아웃 시 공용 워크스페이스로 이동
  apps/frontend/src/features/auth/model/authMutations.ts
Labels: 🐰🐣 FE, ✨ Feature

#400 같은 clientId에 대한 커서 필터
  apps/frontend/src/features/canvas/ui/CollaborativeCursors/index.tsx
Labels: 🐰🐣 FE, 🐛 Bug

#402 README 제목 수정
  README.md
Labels: 📑 Documentation

#403 README 최종 수정
  README.md
Labels: 📑 Documentation

#407 각종 이슈 해결
  apps/backend/src/app.controller.ts
  apps/backend/src/page/page.service.ts
  apps/backend/src/tasks/tasks.service.ts
  apps/backend/src/workspace/workspace.module.ts
  apps/backend/src/workspace/workspace.service.ts
  apps/websocket/src/app.controller.ts
  apps/websocket/src/yjs/yjs.service.ts
  services/nginx/conf.d/prod_nginx.conf
  services/nginx/conf.d/prod_nginx_init.conf
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#408 fix: swagger production 환경에서는 비활성화
  apps/backend/src/main.ts
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#412 예외 처리를 강화하고 API 호출 최적화
  apps/websocket/src/yjs/yjs.service.ts
Labels: ✨ Feature, 🐧🚀😶‍🌫️ BE, 🐛 Bug

#406 페이지 생성 시, DB에 워크스페이스 id가 저장 안되는 버그
  apps/frontend/src/entities/page/model/pageMutations.ts
  apps/frontend/src/entities/page/model/pageTypes.ts
  apps/frontend/src/features/canvasTools/index.ts
  apps/frontend/src/features/canvasTools/ui/NewNodePanel/index.tsx
  apps/frontend/src/features/pageSidebar/ui/ProfileModal/index.tsx
  apps/frontend/src/features/pageSidebar/ui/Tools/index.tsx
Labels: 🐰🐣 FE, 🐛 Bug

#417 초기 사이트 접속 시 에디터 소켓 접속하는 문제 해결
  apps/frontend/src/features/editor/model/useEditorConnection.ts
Labels: 🐰🐣 FE, 🐛 Bug
