Repository boostcampwm-2024/web15-OctoDocs, pull requests merged in 2024-11, with the labels that each got.

#33 chore: nestjs 설치
  backend/.eslintrc.js
  backend/.gitignore
  backend/.prettierrc
  backend/README.md
  backend/nest-cli.json
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/tsconfig.build.json
  backend/tsconfig.json
  backend/yarn.lock
Labels: BE, Feature

#35 스타일링 초기 세팅
  frontend/.prettierrc
  frontend/package.json
  frontend/src/assets/fonts/Pretendard-Bold.subset.woff2
  frontend/src/assets/fonts/Pretendard-Medium.subset.woff2
  frontend/src/assets/fonts/Pretendard-SemiBold.subset.woff2
  frontend/src/index.css
  frontend/src/lib/utils.ts
  frontend/tailwind.config.js
Labels: FE, Feature

#38 공용 divider 컴포넌트 구현
  frontend/src/components/commons/divider/HorizontalDivider.tsx
  frontend/src/components/commons/divider/VerticalDivider.tsx
  frontend/tailwind.config.js
Labels: FE, Feature

#39 HoverTrigger 컴포넌트 구현
  frontend/public/logo.png
  frontend/src/components/HoverTrigger.tsx
  frontend/src/components/LogoBtn.tsx
  frontend/src/components/WorkspaceNav.tsx
  frontend/src/components/sidebar/NoteList.tsx
  frontend/src/components/sidebar/TopNav.tsx
  frontend/src/components/sidebar/index.tsx
  frontend/tailwind.config.js
Labels: FE, Feature

#40 TypeORM 설정 & Entity 설계
  backend/.gitignore
  backend/package.json
  backend/src/app.module.ts
  backend/src/edge/edge.controller.spec.ts
  backend/src/edge/edge.controller.ts
  backend/src/edge/edge.entity.ts
  backend/src/edge/edge.module.ts
  backend/src/edge/edge.repository.ts
  backend/src/edge/edge.service.spec.ts
  backend/src/edge/edge.service.ts
  backend/src/node/node.controller.spec.ts
  backend/src/node/node.controller.ts
  backend/src/node/node.entity.ts
  backend/src/node/node.module.ts
  backend/src/node/node.repository.ts
  backend/src/node/node.service.spec.ts
  backend/src/node/node.service.ts
  backend/src/page/page.controller.spec.ts
  backend/src/page/page.controller.ts
  backend/src/page/page.entity.ts
  backend/src/page/page.module.ts
  backend/src/page/page.repository.ts
  backend/src/page/page.service.spec.ts
  backend/src/page/page.service.ts
  backend/yarn.lock
Labels: BE, Feature

#43 에디터 컴포넌트 추가
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/editor/content.ts
  frontend/src/components/editor/extensions.ts
  frontend/src/components/editor/index.tsx
  frontend/src/components/editor/prosemirror.css
  frontend/src/components/editor/slash-commands.tsx
  frontend/src/components/layout/SideWrapper.tsx
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: FE, Feature

#44 사이드바, 에디터 컴포넌트 구현
  README.md
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package.json
  frontend/public/logo.png
  frontend/public/vite.svg
  frontend/src/App.tsx
  frontend/src/assets/fonts/Pretendard-Bold.subset.woff2
  frontend/src/assets/fonts/Pretendard-Medium.subset.woff2
  frontend/src/assets/fonts/Pretendard-SemiBold.subset.woff2
  frontend/src/components/HoverTrigger.tsx
  frontend/src/components/LogoBtn.tsx
  frontend/src/components/WorkspaceNav.tsx
  frontend/src/components/commons/divider/HorizontalDivider.tsx
  frontend/src/components/commons/divider/VerticalDivider.tsx
  frontend/src/components/editor/content.ts
  frontend/src/components/editor/extensions.ts
  frontend/src/components/editor/index.tsx
  frontend/src/components/editor/prosemirror.css
  frontend/src/components/editor/slash-commands.tsx
  frontend/src/components/layout/SideWrapper.tsx
  frontend/src/components/sidebar/NoteList.tsx
  frontend/src/components/sidebar/TopNav.tsx
  frontend/src/components/sidebar/index.tsx
  frontend/src/index.css
  frontend/src/lib/utils.ts
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: FE, Feature

#46 에디터 컴포넌트에 기능 추가
  frontend/components.json
  frontend/package.json
  frontend/src/components/editor/content.ts
  frontend/src/components/editor/extensions.ts
  frontend/src/components/editor/index.tsx
  frontend/src/components/editor/selectors/color-selector.tsx
  frontend/src/components/editor/selectors/link-selector.tsx
  frontend/src/components/editor/selectors/math-selector.tsx
  frontend/src/components/editor/selectors/node-selector.tsx
  frontend/src/components/editor/selectors/text-buttons.tsx
  frontend/src/components/editor/slash-commands.tsx
  frontend/src/components/editor/ui/button.tsx
  frontend/src/components/editor/ui/command.tsx
  frontend/src/components/editor/ui/dialog.tsx
  frontend/src/components/editor/ui/icons/crazy-spinner.tsx
  frontend/src/components/editor/ui/icons/font-default.tsx
  frontend/src/components/editor/ui/icons/font-mono.tsx
  frontend/src/components/editor/ui/icons/font-serif.tsx
  frontend/src/components/editor/ui/icons/index.tsx
  frontend/src/components/editor/ui/icons/loading-circle.tsx
  frontend/src/components/editor/ui/icons/magic.tsx
  frontend/src/components/editor/ui/menu.tsx
  frontend/src/components/editor/ui/popover.tsx
  frontend/src/components/editor/ui/scroll-area.tsx
  frontend/src/components/editor/ui/separator.tsx
  frontend/src/components/layout/ScrollWrapper.tsx
  frontend/src/index.css
  frontend/src/types.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: FE, Feature

#50 사이드바 컴포넌트 UI 개선
  frontend/public/logo.png
  frontend/public/workspace-logo.svg
  frontend/src/components/LogoBtn.tsx
  frontend/src/components/WorkspaceNav.tsx
  frontend/src/components/sidebar/NoteList.tsx
  frontend/src/components/sidebar/TopNav.tsx
  frontend/src/components/sidebar/index.tsx
  frontend/src/index.css
Labels: FE, Feature

#48 노드 좌표 반환 API 구현
  backend/src/node/node.controller.ts
  backend/src/node/node.repository.ts
  backend/src/node/node.service.spec.ts
  backend/src/node/node.service.ts
Labels: BE, Feature

#49 페이지 목록 반환 API 구현
  backend/src/page/page.controller.ts
  backend/src/page/page.repository.ts
  backend/src/page/page.service.spec.ts
  backend/src/page/page.service.ts
Labels: BE, Feature

#58 에디터 query, mutation 관련 기능 구현
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/node.ts
  frontend/src/api/page.ts
  frontend/src/components/EditorView.tsx
  frontend/src/components/editor/index.tsx
  frontend/src/components/sidebar/NoteList.tsx
  frontend/src/components/sidebar/Tools.tsx
  frontend/src/components/sidebar/index.tsx
  frontend/src/hooks/useNodes.ts
  frontend/src/hooks/usePages.ts
  frontend/src/lib/axios.ts
  frontend/src/store/usePageStore.ts
  frontend/yarn.lock
Labels: FE, Feature

#62 docs: 프로젝트 소개, 팀원 소개 복구
  README.md
Labels: documentation

#59 fix: node <-> page 순환참조 문제 해결
  backend/src/node/node.module.ts
  backend/src/node/node.service.ts
  backend/src/page/page.entity.ts
  backend/src/page/page.module.ts
  backend/src/page/page.service.ts
Labels: Bug, BE

#65 NoteNode 타입 및 커스텀 컴포넌트 구현, 쿼리 결과로 노드 렌더링 구현
  frontend/src/components/canvas/NoteNode.tsx
  frontend/src/components/canvas/index.tsx
Labels: FE, Feature

#67 에디터 content 자동 저장 기능 추가
  frontend/src/api/page.ts
  frontend/src/components/editor/index.tsx
  frontend/src/hooks/usePages.ts
Labels: FE, Feature

#72 삭제 모달 UI 개선, 새 페이지 작성 버튼 색상 변경
  frontend/public/warning-icon.png
  frontend/src/components/commons/button/index.tsx
  frontend/src/components/commons/dialog/index.tsx
  frontend/src/components/sidebar/NoteList.tsx
  frontend/src/components/sidebar/RemoveNoteModal.tsx
  frontend/src/components/sidebar/Tools.tsx
Labels: FE, Feature

#74 프로젝트 메인 이미지 변경
  README.md
Labels: documentation

#77 docs: README에 hits 카운터 추가
  README.md
Labels: documentation

#78 커스텀 예외 필터 구현
  backend/src/exception/edge.exception.ts
  backend/src/filter/http-exception.filter.ts
  backend/src/main.ts
Labels: BE, Feature

#79 Sidebar 컴포넌트에서 text 선택이 불가능하게 수정
  frontend/src/components/commons/button/index.tsx
  frontend/src/components/sidebar/NoteList.tsx
  frontend/src/components/sidebar/Tools.tsx
Labels: FE, Bug

#84 사이드바 페이지 목록 text overflow 수정
  frontend/src/components/sidebar/NoteList.tsx
Labels: FE, Bug

#88 기본 커서 컴포넌트 추가
  frontend/package.json
  frontend/src/components/cursor/index.tsx
  frontend/yarn.lock
Labels: FE, Feature

#82 EditorTitle 컴포넌트 추가
  frontend/src/App.tsx
  frontend/src/components/editor/EditorTitle.tsx
  frontend/src/components/editor/EditorView.tsx
  frontend/src/components/editor/index.tsx
  frontend/src/components/editor/ui/SaveStatus.tsx
  frontend/src/components/layout/EditorLayout.tsx
  frontend/src/hooks/usePages.ts
Labels: FE, Feature

#94 try-catch 제거, custom error 추가
  backend/src/exception/node.exception.ts
  backend/src/exception/page.exception.ts
  backend/src/node/node.controller.ts
  backend/src/node/node.service.ts
  backend/src/page/page.controller.ts
  backend/src/page/page.service.ts
Labels: 🐧🚀😶‍🌫️ BE

#96 PR 템플릿 수정, 설명 주석처리
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
Labels: 📚 Documentation

#99 node, page : controller, service 테스트 코드 작성
  backend/src/edge/edge.controller.spec.ts
  backend/src/edge/edge.service.spec.ts
  backend/src/node/node.controller.spec.ts
  backend/src/node/node.controller.ts
  backend/src/node/node.service.spec.ts
  backend/src/node/node.service.ts
  backend/src/page/page.controller.spec.ts
  backend/src/page/page.controller.ts
  backend/src/page/page.service.spec.ts
  backend/src/page/page.service.ts
Labels: 🐧🚀😶‍🌫️ BE, 📝 Test

#101 dto 분리, 유효성 검사 추가
  backend/src/node/dtos/createNode.dto.ts
  backend/src/node/dtos/updateNode.dto.ts
  backend/src/node/node.controller.spec.ts
  backend/src/node/node.controller.ts
  backend/src/node/node.dto.ts
  backend/src/node/node.service.spec.ts
  backend/src/node/node.service.ts
  backend/src/page/dtos/createPage.dto.ts
  backend/src/page/dtos/updatePage.dto.ts
  backend/src/page/page.controller.spec.ts
  backend/src/page/page.controller.ts
  backend/src/page/page.dto.ts
  backend/src/page/page.service.spec.ts
  backend/src/page/page.service.ts
Labels: 🆕 Feature, 🐧🚀😶‍🌫️ BE

#103 백엔드 브랜치를 메인으로 머지
  .vscode/settings.json
  backend/src/edge/edge.controller.spec.ts
  backend/src/edge/edge.service.spec.ts
  backend/src/exception/edge.exception.ts
  backend/src/exception/node.exception.ts
  backend/src/exception/page.exception.ts
  backend/src/filter/http-exception.filter.ts
  backend/src/main.ts
  backend/src/node/dtos/createNode.dto.ts
  backend/src/node/dtos/updateNode.dto.ts
  backend/src/node/node.controller.spec.ts
  backend/src/node/node.controller.ts
  backend/src/node/node.entity.ts
  backend/src/node/node.module.ts
  backend/src/node/node.repository.ts
  backend/src/node/node.service.spec.ts
  backend/src/node/node.service.ts
  backend/src/page/dtos/createPage.dto.ts
  backend/src/page/dtos/updatePage.dto.ts
  backend/src/page/page.controller.spec.ts
  backend/src/page/page.controller.ts
  backend/src/page/page.entity.ts
  backend/src/page/page.module.ts
  backend/src/page/page.repository.ts
  backend/src/page/page.service.spec.ts
  backend/src/page/page.service.ts
  frontend/.gitignore
  node_modules/.yarn-integrity
  yarn.lock
Labels: 🐧🚀😶‍🌫️ BE, ♻️ Refactor

#104 dev-fe 브랜치 메인으로 머지
  frontend/components.json
  frontend/package.json
  frontend/public/logo.png
  frontend/public/warning-icon.png
  frontend/public/workspace-logo.svg
  frontend/src/App.tsx
  frontend/src/api/node.ts
  frontend/src/api/page.ts
  frontend/src/components/EditorView.tsx
  frontend/src/components/LogoBtn.tsx
  frontend/src/components/WorkspaceNav.tsx
  frontend/src/components/canvas/NoteNode.tsx
  frontend/src/components/canvas/index.tsx
  frontend/src/components/commons/button/index.tsx
  frontend/src/components/commons/dialog/index.tsx
  frontend/src/components/cursor/index.tsx
  frontend/src/components/editor/EditorTitle.tsx
  frontend/src/components/editor/EditorView.tsx
  frontend/src/components/editor/content.ts
  frontend/src/components/editor/extensions.ts
  frontend/src/components/editor/index.tsx
  frontend/src/components/editor/selectors/color-selector.tsx
  frontend/src/components/editor/selectors/link-selector.tsx
  frontend/src/components/editor/selectors/math-selector.tsx
  frontend/src/components/editor/selectors/node-selector.tsx
  frontend/src/components/editor/selectors/text-buttons.tsx
  frontend/src/components/editor/slash-commands.tsx
  frontend/src/components/editor/ui/SaveStatus.tsx
  frontend/src/components/editor/ui/button.tsx
  frontend/src/components/editor/ui/command.tsx
  frontend/src/components/editor/ui/dialog.tsx
  frontend/src/components/editor/ui/icons/crazy-spinner.tsx
  frontend/src/components/editor/ui/icons/font-default.tsx
  frontend/src/components/editor/ui/icons/font-mono.tsx
  frontend/src/components/editor/ui/icons/font-serif.tsx
  frontend/src/components/editor/ui/icons/index.tsx
  frontend/src/components/editor/ui/icons/loading-circle.tsx
  frontend/src/components/editor/ui/icons/magic.tsx
  frontend/src/components/editor/ui/menu.tsx
  frontend/src/components/editor/ui/popover.tsx
  frontend/src/components/editor/ui/scroll-area.tsx
  frontend/src/components/editor/ui/separator.tsx
  frontend/src/components/layout/EditorLayout.tsx
  frontend/src/components/layout/ScrollWrapper.tsx
  frontend/src/components/sidebar/NoteList.tsx
  frontend/src/components/sidebar/RemoveNoteModal.tsx
  frontend/src/components/sidebar/Tools.tsx
  frontend/src/components/sidebar/TopNav.tsx
  frontend/src/components/sidebar/index.tsx
  frontend/src/hooks/useNodes.ts
  frontend/src/hooks/useNoteList.ts
  frontend/src/hooks/usePages.ts
  frontend/src/index.css
  frontend/src/lib/axios.ts
  frontend/src/store/usePageStore.ts
  frontend/src/types.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 🐳🐣 FE, ♻️ Refactor

#108 API 명세 변경에 따른 쿼리 수정
  frontend/src/api/node.ts
  frontend/src/api/page.ts
  frontend/src/components/EditorView.tsx
  frontend/src/components/canvas/index.tsx
  frontend/src/components/editor/EditorView.tsx
  frontend/src/components/sidebar/NoteList.tsx
  frontend/src/components/sidebar/Tools.tsx
  frontend/src/hooks/useNodes.ts
  frontend/src/hooks/useNoteList.ts
  frontend/src/hooks/usePages.ts
Labels: 🐳🐣 FE, 🐛 Bug

#112 swagger 적용 완료
  backend/db_name
  backend/package.json
  backend/src/main.ts
  backend/src/node/dtos/coordinateResponse.dto.ts
  backend/src/node/dtos/createNode.dto.ts
  backend/src/node/dtos/messageResponse.dto.ts
  backend/src/node/dtos/updateNode.dto.ts
  backend/src/node/node.controller.ts
  backend/src/page/dtos/createPage.dto.ts
  backend/src/page/dtos/findPageResponse.dto.ts
  backend/src/page/dtos/findPagesResponse.dto.ts
  backend/src/page/dtos/messageResponse.dto.ts
  backend/src/page/dtos/updatePage.dto.ts
  backend/src/page/page.controller.ts
  backend/yarn.lock
Labels: 📚 Documentation, 🐧🚀😶‍🌫️ BE, ♻️ Refactor

#117 yjs와 웹소켓을 이용한 동시 편집 기능 추가
  frontend/package.json
  frontend/src/components/editor/EditorTitle.tsx
  frontend/src/components/editor/EditorView.tsx
  frontend/src/components/editor/index.tsx
  frontend/src/index.css
  frontend/yarn.lock
Labels: 🐳🐣 FE, 🆕 Feature

#113 노드 이동 API 구현
  backend/src/node/dtos/moveNode.dto.ts
  backend/src/node/node.controller.spec.ts
  backend/src/node/node.controller.ts
  backend/src/node/node.service.spec.ts
  backend/src/node/node.service.ts
Labels: 🆕 Feature, 🐧🚀😶‍🌫️ BE

#119 y-websocket을 사용한 웹소켓 서버 구현
  backend/package.json
  backend/src/app.module.ts
  backend/src/main.ts
  backend/src/yjs/yjs.module.ts
  backend/src/yjs/yjs.service.ts
  backend/yarn.lock
Labels: 🐳🐣 FE, 🐧🚀😶‍🌫️ BE

#121 필요 없는 파일 제거 및 CI 구성
  .github/workflows/auto-assign-merge.yml
  .github/workflows/ci-pipeline.yml
  .gitignore
  .vscode/settings.json
  backend/db_name
  frontend/.gitignore
  node_modules/.yarn-integrity
  yarn.lock
Labels: 🐳🐣 FE, 🐧🚀😶‍🌫️ BE, ♻️ Refactor

#120 노드 조회, 노드 전체 조회 api 구현
  backend/src/node/dtos/findNodeResponse.dto.ts
  backend/src/node/dtos/findNodesResponse.dto..ts
  backend/src/node/node.controller.ts
  backend/src/node/node.service.spec.ts
  backend/src/node/node.service.ts
  backend/src/page/dtos/findPageResponse.dto.ts
  backend/src/page/page.controller.ts
  backend/src/page/page.entity.ts
Labels: 🆕 Feature, 🐧🚀😶‍🌫️ BE

#126 여러 에디터에서 동시 편집이 안되는 문제 해결
  backend/src/main.ts
  frontend/src/App.tsx
  frontend/src/components/EditorView.tsx
  frontend/src/components/editor/EditorTitle.tsx
  frontend/src/components/editor/EditorView.tsx
  frontend/src/components/editor/index.tsx
  frontend/src/hooks/useNoteList.ts
Labels: 🐳🐣 FE, 🐛 Bug

#127 Page DB Column 추가
  backend/src/node/node.controller.ts
  backend/src/node/node.service.spec.ts
  backend/src/page/page.controller.spec.ts
  backend/src/page/page.entity.ts
  backend/src/page/page.service.spec.ts
Labels: 🆕 Feature, 🐧🚀😶‍🌫️ BE, ♻️ Refactor

#136 .env 파일 전송
  .github/workflows/main.yml
  deploy.sh
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#132 기존 캔버스 뷰에 소켓 기능 추가
  backend/db.sqlite
  backend/src/main.ts
  frontend/src/components/canvas/index.tsx
Labels: 🐳🐣 FE, 🆕 Feature

#140 에디터 추가 시, 커서 익스텐션과 충돌나는 문제 해결
  frontend/src/components/editor/index.tsx
Labels: 🐳🐣 FE, 🐛 Bug

#142 환경 변수를 통한 API 및 웹 서버 URL 관리
  frontend/src/components/EditorView.tsx
  frontend/src/components/canvas/index.tsx
Labels: 🐳🐣 FE, 🆕 Feature

#138 불필요한 db.sqlite 파일 제거
  backend/db.sqlite
Labels: ♻️ Refactor

#116 lint 에러 수정
  frontend/src/components/editor/ui/command.tsx
Labels: 🐳🐣 FE, 🐛 Bug

#152 에디터 업데이트 시 노드에 반영하는 기능 추가
  frontend/package.json
  frontend/src/components/EditorView.tsx
  frontend/src/components/canvas/index.tsx
  frontend/src/components/editor/EditorTitle.tsx
  frontend/src/hooks/useYText.ts
  frontend/src/store/useYDocStore.ts
  frontend/yarn.lock
Labels: 🐳🐣 FE, 🆕 Feature

#154 lint 오류 해결
  frontend/src/hooks/useYText.ts
Labels: 🐳🐣 FE, 🐛 Bug

#155 서버 배포 과정 로깅
  .github/workflows/main.yml
  deploy.sh
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#151 백엔드 단위테스트가 실패하는 문제
  backend/src/edge/edge.service.spec.ts
  backend/src/edge/edge.service.ts
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#149 CI 스크립트(자동 병합, 리뷰어 지정) 실행 시점 수정
  .github/workflows/auto-assign-merge.yml
Labels: 🐳🐣 FE, 🐧🚀😶‍🌫️ BE, 🐛 Bug

#157 fix: DEVELOPMENT_FE_ENV 추가
  .github/workflows/main.yml
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#158 노드들이 한번에 움직이는 문제 수정
  frontend/src/components/canvas/index.tsx
Labels: 🐳🐣 FE, 🐛 Bug

#162 사이드바에 ScrollWrapper 적용
  frontend/src/App.tsx
  frontend/src/components/layout/ScrollWrapper.tsx
Labels: 🐳🐣 FE, 🐛 Bug

#164 에디터 컴포넌트의 디버깅용 텍스트 제거
  frontend/src/components/EditorView.tsx
Labels: 🐳🐣 FE, 🐛 Bug

#166 에디터에 패널 open/close 기능 추가
  frontend/src/App.tsx
  frontend/src/components/layout/EditorLayout.tsx
  frontend/src/components/layout/SideWrapper.tsx
  frontend/src/store/usePageStore.ts
Labels: 🐳🐣 FE, 🆕 Feature

#170 리드미 1차 개선
  README.md
Labels: 📚 Documentation

#172 첫 렌더링 시 pages 쿼리 중복 요청 수정
  frontend/src/components/canvas/index.tsx
Labels: 🐳🐣 FE, 🐛 Bug

#176 README에 문어 추가
  README.md
Labels: 📚 Documentation

#180 wiki, backlog 뱃지 추가
  README.md
Labels: 📚 Documentation

#178 에디터 블록 drag handle이 예상과 다른 곳에 위치하는 문제 수정
  frontend/src/components/layout/EditorLayout.tsx
Labels: 🐳🐣 FE, 🐛 Bug

#184 다른 사용자의 커서들을 표시
  frontend/src/components/CursorView.tsx
  frontend/src/components/canvas/index.tsx
  frontend/src/components/cursor/index.tsx
  frontend/src/hooks/useCursor.ts
Labels: 🐳🐣 FE, 🆕 Feature

#187 websocket 서버를 SocketIO로 변경
  apps/backend/db
  apps/backend/package.json
  apps/backend/src/main.ts
  apps/backend/src/yjs/yjs.service.ts
  apps/frontend/package.json
  apps/frontend/src/components/EditorView.tsx
  apps/frontend/src/components/canvas/index.tsx
  apps/frontend/src/components/editor/index.tsx
  apps/frontend/src/hooks/useCursor.ts
  yarn.lock
Labels: 🐳🐣 FE, 🐧🚀😶‍🌫️ BE, ♻️ Refactor

#191 엣지 API, DB 스키마 업데이트
  .gitignore
  apps/backend/src/edge/dtos/createEdge.dto.ts
  apps/backend/src/edge/dtos/findEdgesResponse.dto.ts
  apps/backend/src/edge/edge.entity.ts
  apps/backend/src/edge/edge.service.ts
Labels: 🆕 Feature, 🐧🚀😶‍🌫️ BE

#193 엣지 API 테스트코드 작성
  .gitignore
  .vscode/settings.json
  apps/backend/src/edge/edge.controller.spec.ts
  apps/backend/src/edge/edge.controller.ts
  apps/backend/src/edge/edge.entity.ts
  apps/backend/src/edge/edge.service.spec.ts
Labels: 🐧🚀😶‍🌫️ BE, 📝 Test

#195 새로운 페이지 열 때 이전 페이지의 웹소켓 연결 끊기 기능
  apps/frontend/src/components/EditorView.tsx
Labels: 🐳🐣 FE, ♻️ Refactor

#194 DB 데이터 저장 구현
  .gitignore
  apps/backend/db
  apps/backend/package.json
  apps/backend/src/node-cache/node-cache.module.ts
  apps/backend/src/node-cache/node-cache.service.ts
  apps/backend/src/page/page.service.ts
  apps/backend/src/yjs/yjs.module.ts
  apps/backend/src/yjs/yjs.service.ts
  yarn.lock
Labels: 🆕 Feature, 🐧🚀😶‍🌫️ BE

#201 가장 가까운 핸들에 연결, 노드 간 1개의 엣지만 가능하게 수정
  apps/frontend/src/components/canvas/index.tsx
  apps/frontend/src/lib/getHandlePosition.ts
Labels: 🐳🐣 FE, 🆕 Feature

#202 자동 머지 조건 및 세부동작 수정
  .github/workflows/auto-assign-merge.yml
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#205 node, edge, page 변경 사항 감지 및 데이터베이스 저장
  apps/backend/package.json
  apps/backend/src/edge/edge.module.ts
  apps/backend/src/edge/edge.service.ts
  apps/backend/src/yjs/yjs.module.ts
  apps/backend/src/yjs/yjs.service.ts
Labels: 🆕 Feature, 🐧🚀😶‍🌫️ BE

#208 Y.Doc의 node에 isHolding property 추가
  apps/frontend/src/components/canvas/index.tsx
Labels: 🐳🐣 FE, 🆕 Feature

#210 유저를 관리하기 위한 웹소켓 Room 추가
  apps/frontend/src/App.tsx
  apps/frontend/src/components/CursorView.tsx
  apps/frontend/src/components/EditorView.tsx
  apps/frontend/src/components/canvas/NoteNode.tsx
  apps/frontend/src/components/commons/activeUser/index.tsx
  apps/frontend/src/components/cursor/index.tsx
  apps/frontend/src/hooks/useCursor.ts
  apps/frontend/src/hooks/useSyncedUsers.ts
  apps/frontend/src/lib/utils.ts
  apps/frontend/src/store/useUserStore.ts
Labels: 🐳🐣 FE, 🆕 Feature

#213 에디터 전체화면 기능
  apps/frontend/src/components/EditorView.tsx
  apps/frontend/src/components/editor/EditorActionPanel.tsx
  apps/frontend/src/components/editor/EditorTitle.tsx
  apps/frontend/src/components/editor/prosemirror.css
  apps/frontend/src/components/editor/ui/SaveStatus.tsx
  apps/frontend/src/components/layout/EditorLayout.tsx
  apps/frontend/src/store/usePageStore.ts
Labels: 🐳🐣 FE, 🆕 Feature

#219 프로필 수정 기능 추가, useCursor에서 프로필 사용하게 수정
  apps/frontend/package.json
  apps/frontend/src/components/LogoBtn.tsx
  apps/frontend/src/components/sidebar/ProfileModal.tsx
  apps/frontend/src/components/sidebar/TopNav.tsx
  apps/frontend/src/hooks/useCursor.ts
  yarn.lock
Labels: 🐳🐣 FE, 🆕 Feature

#218 node, edge, page content 상태 초기화
  apps/backend/src/node/node.service.ts
  apps/backend/src/yjs/yjs.class.ts
  apps/backend/src/yjs/yjs.schema.ts
  apps/backend/src/yjs/yjs.service.spec.ts
  apps/backend/src/yjs/yjs.service.ts
  apps/backend/src/yjs/yjs.type.ts
  apps/backend/yarn.lock
  apps/frontend/src/components/EditorView.tsx
  apps/frontend/src/components/editor/index.tsx
  apps/frontend/yarn.lock
  yarn.lock
Labels: 🆕 Feature, 🐧🚀😶‍🌫️ BE

#221 에디터에서 이미지 업로드하는 기능
  apps/frontend/src/api/imageUpload.ts
  apps/frontend/src/components/editor/index.tsx
  apps/frontend/src/components/editor/slash-commands.tsx
  apps/frontend/src/lib/upload.ts
Labels: 🐳🐣 FE, 🆕 Feature

#225 document name 파싱 이슈 해결
  apps/backend/src/yjs/yjs.service.ts
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#220 로그인, 회원가입 구현
  apps/backend/package.json
  apps/backend/src/app.module.ts
  apps/backend/src/auth/auth.controller.spec.ts
  apps/backend/src/auth/auth.controller.ts
  apps/backend/src/auth/auth.module.ts
  apps/backend/src/auth/auth.service.spec.ts
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/auth/dto/createUser.dto.ts
  apps/backend/src/auth/strategies/kakao.strategy.ts
  apps/backend/src/auth/strategies/naver.strategy.ts
  apps/backend/src/exception/user.exception.ts
  apps/backend/src/user/user.entity.ts
  apps/backend/src/user/user.module.ts
  apps/backend/src/user/user.repository.ts
  apps/backend/src/yjs/yjs.service.spec.ts
  apps/frontend/src/components/EditorView.tsx
  apps/frontend/src/components/editor/index.tsx
  yarn.lock
Labels: 🐳🐣 FE, 🆕 Feature, 🐧🚀😶‍🌫️ BE

#227 페이지에 이모지 필드 추가
  apps/backend/src/page/dtos/createPage.dto.ts
  apps/backend/src/page/dtos/updatePage.dto.ts
  apps/backend/src/page/page.controller.spec.ts
  apps/backend/src/page/page.entity.ts
  apps/backend/src/page/page.repository.ts
  apps/backend/src/page/page.service.spec.ts
  apps/backend/src/page/page.service.ts
  apps/backend/src/yjs/yjs.service.spec.ts
Labels: 🆕 Feature, 🐧🚀😶‍🌫️ BE

#228 사이드 바, 에디터 UI/UX 수정
  apps/frontend/package.json
  apps/frontend/public/logo.png
  apps/frontend/src/App.tsx
  apps/frontend/src/components/LogoBtn.tsx
  apps/frontend/src/components/WorkspaceNav.tsx
  apps/frontend/src/components/layout/EditorLayout.tsx
  apps/frontend/src/components/layout/SideWrapper.tsx
  apps/frontend/src/components/sidebar/Tools.tsx
  apps/frontend/src/components/sidebar/TopNav.tsx
  apps/frontend/src/components/sidebar/index.tsx
  apps/frontend/tailwind.config.js
  yarn.lock
Labels: 🐳🐣 FE, 🆕 Feature

#230 커서 이름 표시 바 스타일링
  apps/frontend/src/components/cursor/index.tsx
Labels: 🐳🐣 FE, 🆕 Feature

#234 업데이트 쿼리 디바운싱
  apps/backend/src/node-cache/node-cache.service.ts
  apps/backend/src/yjs/yjs.schema.ts
  apps/backend/src/yjs/yjs.service.ts
  apps/backend/src/yjs/yjs.type.ts
Labels: 🆕 Feature, 🐧🚀😶‍🌫️ BE

#236 이모지 기능 추가
  apps/backend/src/yjs/yjs.service.ts
  apps/backend/src/yjs/yjs.type.ts
  apps/frontend/package.json
  apps/frontend/src/api/node.ts
  apps/frontend/src/api/page.ts
  apps/frontend/src/components/canvas/NoteNode.tsx
  apps/frontend/src/components/canvas/index.tsx
  apps/frontend/src/components/commons/emoji/index.tsx
  apps/frontend/src/components/editor/EditorTitle.tsx
  apps/frontend/src/components/sidebar/NoteList.tsx
  apps/frontend/src/components/sidebar/Tools.tsx
  apps/frontend/src/hooks/useNodes.ts
  apps/frontend/src/hooks/useNoteList.ts
  apps/frontend/src/hooks/usePages.ts
  apps/frontend/src/hooks/useYText.ts
  yarn.lock
Labels: 🐳🐣 FE, 🆕 Feature

#241 에디터 커서에 유저 정보 보여주는 기능 구현
  apps/frontend/src/components/editor/index.tsx
Labels: 🐳🐣 FE, 🆕 Feature

#244 가까운 엣지 계산 최적화
  apps/frontend/src/components/canvas/index.tsx
  apps/frontend/src/lib/calculateBestHandles.ts
Labels: 🐳🐣 FE, 🐛 Bug

#249 이모지 placeholder UI 구현
  apps/frontend/src/components/canvas/NoteNode.tsx
  apps/frontend/src/components/commons/emoji/index.tsx
  apps/frontend/src/components/editor/EditorTitle.tsx
  apps/frontend/src/components/sidebar/NoteList.tsx
Labels: 🐳🐣 FE, 🆕 Feature

#251 에디터에 스크롤바가 올바르게 생기지 않는 문제 수정
  apps/frontend/src/components/editor/EditorActionPanel.tsx
  apps/frontend/src/components/layout/EditorLayout.tsx
Labels: 🐳🐣 FE, 🐛 Bug

#252 JWT 인증, 인가
  apps/backend/package.json
  apps/backend/src/auth/auth.controller.spec.ts
  apps/backend/src/auth/auth.controller.ts
  apps/backend/src/auth/auth.module.ts
  apps/backend/src/auth/auth.service.spec.ts
  apps/backend/src/auth/guards/jwt-auth.guard.ts
  apps/backend/src/exception/invalid.exception.ts
  apps/backend/src/exception/login.exception.ts
  apps/backend/src/exception/user.exception.ts
  yarn.lock
Labels: 🆕 Feature, 🐧🚀😶‍🌫️ BE

#254 노드 드래그 시 select 많이 발생하는 문제 임시 해결
  apps/backend/src/yjs/yjs.service.ts
  apps/frontend/index.html
  apps/frontend/package.json
  yarn.lock
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#256 자동으로 노드 정렬해주는 기능
  apps/frontend/package.json
  apps/frontend/src/components/canvas/index.tsx
  yarn.lock
Labels: 🐳🐣 FE, 🆕 Feature

#267 Popover 공용 컴포넌트 구현
  apps/frontend/src/components/commons/popover/Content.tsx
  apps/frontend/src/components/commons/popover/Trigger.tsx
  apps/frontend/src/components/commons/popover/index.tsx
  apps/frontend/src/hooks/usePopover.ts
  apps/frontend/src/lib/getPopoverPosition.ts
Labels: 🐰🐣 FE, ✨ Feature

#280 변경 사항만 데이터베이스에 반영
  apps/backend/package.json
  apps/backend/src/edge/edge.module.ts
  apps/backend/src/edge/edge.service.ts
  apps/backend/src/node-cache/node-cache.module.ts
  apps/backend/src/node-cache/node-cache.service.ts
  apps/backend/src/node/node.service.ts
  apps/backend/src/page/dtos/updatePage.dto.ts
  apps/backend/src/page/page.service.ts
  apps/backend/src/yjs/yjs.module.ts
  apps/backend/src/yjs/yjs.service.spec.ts
  apps/backend/src/yjs/yjs.service.ts
  apps/frontend/src/features/canvas/model/useCanvas.ts
  apps/frontend/src/features/editor/model/useEditorTitle.ts
  apps/frontend/src/features/editor/ui/EditorTitle/index.tsx
  apps/frontend/src/features/pageSidebar/api/usePages.ts
  apps/frontend/src/features/pageSidebar/ui/Tools/index.tsx
  apps/frontend/src/widgets/EditorView/hooks/useEditorView.ts
  apps/frontend/src/widgets/EditorView/ui/index.tsx
  yarn.lock
Labels: 🐰🐣 FE, ✨ Feature, 🐧🚀😶‍🌫️ BE

#275 새로 생성된 노드 auto-focus
  apps/frontend/src/features/canvas/model/useCanvas.ts
  apps/frontend/src/features/canvas/ui/Node/NoteNode/index.tsx
Labels: 🐰🐣 FE, ✨ Feature

#290 oAuth 인증 후 토큰 response 형식 수정
  apps/backend/src/auth/auth.controller.spec.ts
  apps/backend/src/auth/auth.controller.ts
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#292 백엔드 누락된 의존성 추가
  apps/backend/package.json
  yarn.lock
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#282 워크스페이스 구조 추가, 업데이트
  apps/backend/package.json
  apps/backend/src/app.module.ts
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/auth/strategies/naver.strategy.ts
  apps/backend/src/edge/edge.controller.spec.ts
  apps/backend/src/edge/edge.entity.ts
  apps/backend/src/edge/edge.module.ts
  apps/backend/src/edge/edge.repository.ts
  apps/backend/src/edge/edge.service.spec.ts
  apps/backend/src/node/node.entity.ts
  apps/backend/src/node/node.repository.ts
  apps/backend/src/node/node.service.spec.ts
  apps/backend/src/page/page.controller.spec.ts
  apps/backend/src/page/page.entity.ts
  apps/backend/src/page/page.repository.ts
  apps/backend/src/page/page.service.spec.ts
  apps/backend/src/role/role.controller.spec.ts
  apps/backend/src/role/role.controller.ts
  apps/backend/src/role/role.entity.ts
  apps/backend/src/role/role.module.ts
  apps/backend/src/role/role.repository.ts
  apps/backend/src/role/role.service.spec.ts
  apps/backend/src/role/role.service.ts
  apps/backend/src/user/user.entity.ts
  apps/backend/src/workspace/workspace.controller.spec.ts
  apps/backend/src/workspace/workspace.controller.ts
  apps/backend/src/workspace/workspace.entity.ts
  apps/backend/src/workspace/workspace.module.ts
  apps/backend/src/workspace/workspace.repository.ts
  apps/backend/src/workspace/workspace.service.spec.ts
  apps/backend/src/workspace/workspace.service.ts
  yarn.lock
Labels: ✨ Feature, 🐧🚀😶‍🌫️ BE

#298 undefined id 이슈 해결
  apps/backend/src/yjs/yjs.service.ts
  yarn.lock
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#293 JWT 인증방식 쿠키로 변경
  apps/backend/package.json
  apps/backend/src/auth/auth.controller.spec.ts
  apps/backend/src/auth/auth.controller.ts
  apps/backend/src/auth/auth.module.ts
  apps/backend/src/auth/auth.service.spec.ts
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/auth/dtos/messageResponse.dto.ts
  apps/backend/src/auth/dtos/signUp.dto.ts
  apps/backend/src/auth/guards/jwt-auth.guard.ts
  apps/backend/src/auth/strategies/kakao.strategy.ts
  apps/backend/src/auth/strategies/naver.strategy.ts
  apps/backend/src/auth/token/token.module.ts
  apps/backend/src/auth/token/token.service.ts
  apps/backend/src/main.ts
  apps/backend/src/role/role.controller.spec.ts
  apps/backend/src/role/role.controller.ts
  apps/backend/src/role/role.module.ts
  services/nginx/ssl/localhost.crt
  services/nginx/ssl/localhost.key
  yarn.lock
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#301 로컬 개발환경 편의성 개선
  .gitignore
  apps/backend/package.json
  apps/backend/src/app.module.ts
  apps/backend/tsconfig.json
  apps/frontend/package.json
  apps/frontend/vite.config.ts
  compose.local.yml
  package.json
  services/backend/Dockerfile.local
  services/nginx/Dockerfile.local
  services/nginx/conf.d/default.conf
  turbo.json
Labels: 🐰🐣 FE, ✨ Feature, 🐧🚀😶‍🌫️ BE, 🐛 Bug

#305 ssl 키 삭제
  services/nginx/ssl/localhost.crt
  services/nginx/ssl/localhost.key
Labels: 🐛 Bug

#289 tanstack 라우터 추가, 워크 스페이스 및 소켓 룸 분리
  apps/frontend/.prettierrc
  apps/frontend/eslint.config.js
  apps/frontend/package.json
  apps/frontend/src/app/App.tsx
  apps/frontend/src/app/main.tsx
  apps/frontend/src/features/canvas/model/useCanvas.ts
  apps/frontend/src/features/canvas/model/useCollaborativeCursors.ts
  apps/frontend/src/routeTree.gen.ts
  apps/frontend/src/routes/__root.tsx
  apps/frontend/src/routes/index.tsx
  apps/frontend/src/routes/workspace/$workspaceId.tsx
  apps/frontend/src/shared/lib/useWorkspace.ts
  apps/frontend/vite.config.ts
  yarn.lock
Labels: 🐰🐣 FE, ✨ Feature

#296 Popover 컴포넌트의 usePopover에 close 기능 추가
  apps/frontend/src/shared/model/usePopover.ts
  apps/frontend/src/shared/ui/Popover/index.tsx
  yarn.lock
Labels: 🐰🐣 FE, ✨ Feature

#303 workspace 관련 api 완성, 서비스 코드 수정
  apps/backend/src/edge/dtos/findEdgesResponse.dto.ts
  apps/backend/src/edge/edge.controller.spec.ts
  apps/backend/src/edge/edge.controller.ts
  apps/backend/src/edge/edge.module.ts
  apps/backend/src/edge/edge.service.spec.ts
  apps/backend/src/edge/edge.service.ts
  apps/backend/src/exception/user.exception.ts
  apps/backend/src/exception/workspace-auth.exception.ts
  apps/backend/src/exception/workspace.exception.ts
  apps/backend/src/node/node.controller.spec.ts
  apps/backend/src/node/node.controller.ts
  apps/backend/src/node/node.module.ts
  apps/backend/src/node/node.service.spec.ts
  apps/backend/src/node/node.service.ts
  apps/backend/src/page/dtos/createPage.dto.ts
  apps/backend/src/page/page.controller.spec.ts
  apps/backend/src/page/page.controller.ts
  apps/backend/src/page/page.module.ts
  apps/backend/src/page/page.repository.ts
  apps/backend/src/page/page.service.spec.ts
  apps/backend/src/page/page.service.ts
  apps/backend/src/role/role.controller.spec.ts
  apps/backend/src/workspace/dtos/createWorkspace.dto.ts
  apps/backend/src/workspace/dtos/createWorkspaceResponse.dto.ts
  apps/backend/src/workspace/dtos/getUserWorkspacesResponse.dto.ts
  apps/backend/src/workspace/dtos/messageResponse.dto.ts
  apps/backend/src/workspace/dtos/userWorkspace.dto.ts
  apps/backend/src/workspace/workspace.controller.spec.ts
  apps/backend/src/workspace/workspace.controller.ts
  apps/backend/src/workspace/workspace.module.ts
  apps/backend/src/workspace/workspace.service.spec.ts
  apps/backend/src/workspace/workspace.service.ts
  apps/backend/src/yjs/yjs.service.ts
Labels: ✨ Feature, 🐧🚀😶‍🌫️ BE

#308 focus시 줌 상태 유지
  apps/frontend/src/features/canvas/model/useCanvas.ts
Labels: 🐰🐣 FE, ✨ Feature

#311 권한 관련 api 구현
  apps/backend/src/auth/auth.controller.spec.ts
  apps/backend/src/auth/auth.controller.ts
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/auth/token/token.service.ts
  apps/backend/src/exception/access.exception.ts
  apps/backend/src/exception/role-duplicate.exception.ts
  apps/backend/src/exception/workspace-auth.exception.ts
  apps/backend/src/workspace/dtos/createWorkspaceInviteUrl.dto.ts
  apps/backend/src/workspace/dtos/getUserWorkspacesResponse.dto.ts
  apps/backend/src/workspace/workspace.controller.spec.ts
  apps/backend/src/workspace/workspace.controller.ts
  apps/backend/src/workspace/workspace.module.ts
  apps/backend/src/workspace/workspace.service.spec.ts
  apps/backend/src/workspace/workspace.service.ts
  yarn.lock
Labels: ✨ Feature, 🐧🚀😶‍🌫️ BE

#325 워크스페이스 api 추가, 수정
  apps/backend/src/workspace/dtos/getUserWorkspacesResponse.dto.ts
  apps/backend/src/workspace/dtos/userWorkspace.dto.ts
  apps/backend/src/workspace/workspace.controller.spec.ts
  apps/backend/src/workspace/workspace.controller.ts
  apps/backend/src/workspace/workspace.service.spec.ts
  apps/backend/src/workspace/workspace.service.ts
Labels: ✨ Feature, 🐧🚀😶‍🌫️ BE

#321 snowflakeId 자동생성 버그
  apps/backend/src/auth/auth.service.spec.ts
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/auth/token/token.service.ts
  apps/backend/src/edge/edge.service.spec.ts
  apps/backend/src/page/page.service.spec.ts
  apps/backend/src/user/user.entity.ts
  apps/backend/src/workspace/workspace.entity.ts
  apps/backend/src/workspace/workspace.service.spec.ts
  apps/backend/src/workspace/workspace.service.ts
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#330 Production 환경 구성
  apps/backend/src/main.ts
  compose.init.yml
  compose.prod.yml
  services/backend/Dockerfile.prod
  services/nginx/conf.d/prod_nginx.conf
  services/nginx/conf.d/prod_nginx_init.conf
Labels: ✨ Feature, 🐧🚀😶‍🌫️ BE

#329 초기 데이터 세팅 이슈 해결
  apps/backend/src/node/node.repository.ts
  apps/backend/src/node/node.service.spec.ts
  apps/backend/src/yjs/yjs.service.ts
Labels: 🐧🚀😶‍🌫️ BE, 🐛 Bug

#334 초기 렌더링 문제 해결
  apps/frontend/src/app/App.tsx
  apps/frontend/src/entities/page/api/pageApi.ts
  apps/frontend/src/features/canvas/model/useCanvas.ts
  apps/frontend/src/features/pageSidebar/api/usePages.ts
  apps/frontend/src/features/pageSidebar/ui/Tools/index.tsx
  apps/frontend/src/routeTree.gen.ts
Labels: 🐰🐣 FE, 🐛 Bug

#332 노드맵 초기화 로직 초기화
  apps/backend/src/app.module.ts
  apps/frontend/src/features/canvas/model/calculateHandles.ts
  apps/frontend/src/features/canvas/model/useCanvas.ts
  apps/frontend/src/features/canvas/model/useCollaborativeCursors.ts
  apps/frontend/src/features/pageSidebar/model/useNoteList.ts
  apps/frontend/src/features/pageSidebar/ui/Tools/index.tsx
  apps/frontend/src/widgets/CanvasToolsView/ui/index.tsx
Labels: 🐰🐣 FE, 🐛 Bug

#328 현재 참여하고 있는 워크스페이스 이름 표기
  apps/frontend/src/widgets/TopNavView/ui/index.tsx
Labels: 🐰🐣 FE, ✨ Feature

#339 소켓 룸 이름 통일
  apps/frontend/src/features/canvas/model/useCanvas.ts
  apps/frontend/src/features/canvas/model/useCollaborativeCursors.ts
  apps/frontend/src/features/workspace/ui/ShareTool/SharePanel.tsx
  apps/frontend/src/routes/join/index.tsx
Labels: 🐰🐣 FE, 🐛 Bug
